spring:
  application:
    name: productapp
  datasource:
    url: jdbc:hsqldb:mem:productdb
    driverClassNname: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
  console.enabled: true
  console.path: /h2-console
  profiles: local
  kafka:
    template:
      default-topic: producer-event
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: product-events-listener-group
rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #queue: product_queue
    #exchange: product_exchange
    #routing: product_routing_key