spring:
  application:
    name: productapp
  profiles: local
  kafka:
    template:
      default-topic: producer-event
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #queue: product_queue
    #exchange: product_exchange
    #routing: product_routing_key